image: php:8.1
 
pipelines:
    branches:
        main:
            - step:
                name: Build and check php version
                size: 4x
                runtime:
                    cloud:
                        atlassian-ip-ranges: true
                script:
                    - php -v
            - step:
                name: Deploy To Live
                size: 4x
                runtime:
                    cloud:
                        atlassian-ip-ranges: true
                deployment: production
                trigger: manual
                caches:
                    - git-ftp
                script:
                    - apt-get update
                    - apt-get -qq install git-ftp
                    - >
                        echo Public IP of this pipeline is: $(curl -s ifconfig.me)
                    - git ftp init -vv --insecure --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_HOST
 
definitions:
    caches:
        git-ftp: /usr/bin/git-ftp