#!/usr/bin/env python3
"""
Builds the Bootstrap Icons subset the site actually uses.

The full icon font is 131 KB (+ 14 KB of CSS) on every page for 2,078 icons; the site uses about a
hundred. This script scans the repo for `bi-<name>` classes and writes:
  fonts/bootstrap-icons-subset.woff2   only those glyphs
  css/icons.css                         @font-face + only those classes (folded into css/style.min.css by tools/build-assets.sh)

Run it after adding a new icon, then tools/build-assets.sh, and commit the results:
  python3 tools/build-icons.py            rebuild
  python3 tools/build-icons.py --check    fail if a bi-* class used in the repo is missing from css/icons.css (CI; no network)

Needs: pip install fonttools brotli   (rebuild only; --check needs nothing)
"""
import os, re, sys, urllib.request

VERSION = '1.13.1'
BASE = f'https://cdn.jsdelivr.net/npm/bootstrap-icons@{VERSION}/font/'
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
# Icons referenced by code point (slick arrows in css/style.css) or built dynamically.
# Words that look like icon names in code/comments but are not icons.
NON_ICONS = {'directional', 'slice', 'url'}
ALWAYS = ['chevron-left', 'chevron-right', 'x', 'x-lg', 'check', 'check-lg', 'search', 'list', 'arrow-up']

def used_names():
    pat = re.compile(r'\bbi-([a-z0-9]+(?:-[a-z0-9]+)*)')
    names = set(ALWAYS)
    for d, dirs, files in os.walk(ROOT):
        dirs[:] = [x for x in dirs if x not in ('vendor', '.git', 'node_modules', 'phpmailer', 'cache', 'fonts')]
        for f in files:
            if f.endswith(('.php', '.js', '.css', '.html')) and not f.endswith('.min.js') and f not in ('icons.css', 'style.min.css'):
                try:
                    names.update(pat.findall(open(os.path.join(d, f), encoding='utf-8', errors='ignore').read()))
                except OSError:
                    pass
    return names

def fetch(name):
    return urllib.request.urlopen(BASE + name, timeout=60).read()

def main():
    check = '--check' in sys.argv
    names = used_names()
    if check:
        have = set(re.findall(r'\.bi-([a-z0-9-]+)::before', open(os.path.join(ROOT, 'css/icons.css')).read()))
        missing = sorted(n for n in names if n not in have and n not in NON_ICONS)
        if missing:
            print('bi-* classes used in the repo but missing from css/icons.css: ' + ', '.join(missing))
            print('Run: python3 tools/build-icons.py && tools/build-assets.sh  (if the name is not a real icon, add it to NON_ICONS)')
            return 1
        print('icons.css covers every bi-* class in the repo (%d glyphs)' % len(have))
        return 0
    css = fetch('bootstrap-icons.css').decode()
    codes = {m.group(1): m.group(2) for m in re.finditer(r'\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-f]+)"', css)}
    chosen = sorted(n for n in names if n in codes)
    skipped = sorted(n for n in names if n not in codes)
    from fontTools import subset
    from fontTools.ttLib import TTFont
    open('/tmp/bi-full.woff2', 'wb').write(fetch('fonts/bootstrap-icons.woff2'))
    opts = subset.Options(); opts.flavor = 'woff2'; opts.layout_features = []; opts.name_IDs = []; opts.notdef_outline = False
    font = TTFont('/tmp/bi-full.woff2')
    sub = subset.Subsetter(opts); sub.populate(unicodes=[int(codes[n], 16) for n in chosen]); sub.subset(font)
    out = os.path.join(ROOT, 'fonts/bootstrap-icons-subset.woff2')
    font.flavor = 'woff2'; font.save(out)
    base = re.search(r'\.bi::before,\s*\[class\^="bi-"\]::before,\s*\[class\*=" bi-"\]::before\s*\{.*?\}', css, re.S).group(0)
    rules = ''.join('.bi-%s::before { content: "\\%s"; }\n' % (n, codes[n]) for n in chosen)
    face = ('@font-face {\n  font-display: block;\n  font-family: "bootstrap-icons";\n'
            '  src: url("/fonts/bootstrap-icons-subset.woff2?v=%s") format("woff2");\n}\n' % VERSION)
    open(os.path.join(ROOT, 'css/icons.css'), 'w').write('/* Generated by tools/build-icons.py - do not edit. Bootstrap Icons %s (MIT), %d glyphs. */\n%s%s\n%s' % (VERSION, len(chosen), face, base, rules))
    print('subset: %d icons, font %d bytes; names that are not icons: %s' % (len(chosen), os.path.getsize(out), skipped))
    return 0

if __name__ == '__main__':
    sys.exit(main())
